---
title: "Hw2"
author: "Neslihan Caliskan"
date: "2/8/2021"
output: 
  html_document: default
  github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


Load in your packages
```{r Packages}
library(gapminder)
library(tidyverse)
library(dplyr)

```

Exercise 1
```{r Exercise 1.1 & 1.2}
gapminder::gapminder 

#Exercise 1.1 & 1.2
#In order to filter by multiple rows you need to use the "%in%" function!
#You can add more criteria by inserting "&" in the middle.
#You can select multiple columns simply by insterting a comma in between them! 
gapminder %>% 
  filter(country %in% c("Afghanistan","Australia","Austria") & year > 1970 & year < 1980) %>% 
  select(country, gdpPercap) 

```

```{r Exercise 1.3}
gapminder %>% 
  mutate(diffLifeExp = lifeExp - lag(lifeExp)) %>% 
 summarize(diff(diffLifeExp, differences = 1))

```


```{r Exercise 1.4}
gapminder %>% 
  group_by(country) %>% 
  summarize(max(gdpPercap))
```


```{r Exercise 1.5}
gapminder %>% 
  filter(country == "Canada") %>% 
  ggplot +
  aes(x = gdpPercap, y = lifeExp) + 
  geom_point(alpha = 0.5) +
  scale_x_log10("GDP per capita", labels = scales::dollar_format()) +
  theme_bw() +
  scale_y_continuous("Life Expectancy") +
  ggtitle("Life Expectancy vs GP per Capita for Canada")
  
```



