---
title: "Hw2"
author: "Neslihan Caliskan"
date: "2/8/2021"
output: 
  html_document: default
  github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gapminder) # BMW: Put library() calls in the setup chunk.
library(tidyverse)
library(dplyr) # BMW: library(tidyverse) loads dplyr too, so you don't need it as well
library(palmerpenguins)
```


Exercise 1

<!-- BMW: In markdown, you need a blank line between paragphs. A single line break is ignored. -->

```{r Exercise 1.1 & 1.2}
gapminder::gapminder  # BMW: Don't print out whole datasets like this

#Exercise 1.1 & 1.2
#In order to filter by multiple rows you need to use the "%in%" function!
#You can add more criteria by inserting "&" in the middle.
#You can select multiple columns simply by insterting a comma in between them! 
gapminder %>% 
  filter(country %in% c("Afghanistan","Australia","Austria") & year > 1970 & year < 1980) %>% 
  select(country, gdpPercap) 
```

```{r Exercise 1.3}
gapminder %>% 
  group_by(country) %>% 
  mutate(diffLifeExp = lifeExp - lag(lifeExp)) %>% 
  filter(diffLifeExp < lifeExp)
```

<!-- BMW: Great job! You need to group by country so that you don't subtract 2007 from one country from 1952 for the next country. -->

```{r Exercise 1.4}
#A better way to write to code to make it look neater
gapminder %>% 
  group_by(country) %>% 
  filter(gdpPercap == max(gdpPercap)) 
```


```{r Exercise 1.5}
gapminder %>% 
  filter(country == "Canada") %>% 
  ggplot() + 
  aes(x = gdpPercap, y = lifeExp) + 
  geom_point(alpha = 0.5) +
  scale_x_log10("GDP per capita", labels = scales::dollar_format()) +
  theme_bw() +
  scale_y_continuous("Life Expectancy") +
  ggtitle("Life Expectancy vs GP per Capita for Canada")
  
```

Exercise 2 

```{r Packages}
# Put all library() calls at teh top of the script
```

Pick two quantitative variables to explore

```{r Exercise 2.1}
#I couldn't get the first half of this chunk work can you help me with it?
# palmerpenguins::penguins %>% 
#   select(flipper_length_mm, body_mass_g) %>% 
#   summarise(
#     Mean_Length = round(flipper_length_mm, na.rm = TRUE),
#     Mean_BodyMass = round(body_mass_g, na.rm = TRUE),
#     SD_FLength = sd(flipper_length_mm, na.rm = TRUE),
#     SD_BodyMass = sd(body_mass_g, na.rm = TRUE),
#     )

# BMW: round() rounds each number in a vector (each value of flipper_length_mm). Were you trying to round the mean? Then you need, round(mean(flipper_length_mm, na.rm = TRUE))

palmerpenguins::penguins %>% 
  select(bill_length_mm, bill_depth_mm) %>% 
  summarise(
    meanlength = mean(bill_length_mm, na.rm = T),
    sdlength = sd(bill_length_mm, na.rm = T),
    meandepth = mean(bill_depth_mm, na.rm = T),
    sddepth = sd(bill_depth_mm, na.rm = T),
  )

#Scatterplot
palmerpenguins::penguins %>% 
  ggplot() + # BMW: Always put the parentheses on function calls in a pipe, even if you leave them empty.
  aes(x = bill_length_mm, y = bill_depth_mm) +
  geom_point(alpha = 0.5) +
  scale_x_log10("Bill Length") +
  ylab("Bill Depth")
```


```{r Exercise 2.2}
#One categorical and one quantitative variable to explore
palmerpenguins::penguins %>% 
  select(species, body_mass_g) %>% 
  group_by(species) %>% 
  summarise(sample_size = n(), # BMW: The question wanted sample size by group too
            mean_mass = mean(body_mass_g, na.rm = TRUE),
            sd_mass = sd(body_mass_g, na.rm = TRUE)
            )

#Visualize the data
palmerpenguins::penguins %>% 
  ggplot() +
  geom_jitter(aes(x = species, 
                  y = body_mass_g,
                  colour = species),
              alpha = .5, # BMW: parameters that _aren't_ mapped to variables need to be outside aes()
              height = 0
              ) # BMW: When you use geom_jitter() with a continuous and categorical variable, you want to set it to not add noise on the axis with the continous variable. Here, do that by adding height = 0

```

