---
title: "Caliskan_finalproj"
author: "Neslihan Caliskan"
date: "5/1/2021"
output: 
  html_document: default
  github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading in datasets
```{r load in packages}
library(tidyverse)
library(readr)
library(ggplot2)
library(here)
```


```{r}
if ( !dir.exists( here::here("final_project", "data") ) ) {
  dir.create( here::here("final_project", "data", "output", ".R"), recursive = TRUE )
}

```

Loading in csv files
```{r load in csv files}
covid_prison_case <- read_csv(here("data", "covid_prison_cases.csv"))
                       
covid_prison_rate <- read_csv(here("data", "covid_prison_rates.csv"))
                       
covid_population <-  read_csv(here("data", "prison_populations.csv"))
                   
staff_population <-  read_csv(here("data", "staff_populations.csv"))

```


Renamed the column so the names for it wouldn't overlap across different datasets when I join them together.
```{r}
(staff_population %>% 
   rename(staff_april_pop = april_pop))

```

Joining all three datasets together
```{r}
Merged_Covid_Data <- full_join(staff_population, covid_population, by = c("name", "abbreviation")) %>% 
  full_join(covid_prison_case, by = c("name", "abbreviation"))

```

Filtering to see all the Florida data
```{r}
Florida_Data <- covid_prison_case %>% 
  filter(name == "Florida") %>% 
  select(as_of_date, total_staff_cases, total_staff_deaths, total_prisoner_cases, total_prisoner_deaths)
```


```{r}
Staff_Data_FL <- staff_population %>% 
   filter(name == "Florida") %>% 
    select(as_of_date, april_pop)

```


```{r}
Prisoner_Data_FL <- covid_population %>% 
   filter(name == "Florida") 
```


```{r}
